# Generated by Django 3.2.12 on 2022-02-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=10, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.CharField(max_length=50, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='precio'),
        ),
    ]
